### ISSUE TITLE
the gpu used for the experiment

### ISSUE THREAD

**Issue by Adasunnylily** [YueYANG1996/LaBo#6]
hi, I have used the config of cub_base for one shot training on a single 3090, but I kept getting the error of cuda out of memory although I have reduced the batchsize to 4,  i was wondering what GPU did you use for training and any advice of helping me solve this problem? thanks a lot!

**Comment by YueYANG1996** [comment]
Hi,
All experiments (except ImageNet) could be ran on a single GPU with 24GB. The memory requirement for LaBo is quite low, since we just train a linear layer. So I guess your problem should be in the step of precomputing features. Could you show me the entire error message? Thanks!

**Comment by Adasunnylily** [comment]
hi, thanks for your help!!! I have found an error in my settings, now I have solved this problem. Thank u so much!

**Comment by lmg1999** [comment]
> hi, thanks for your help!!! I have found an error in my settings, now I have solved this problem. Thank u so much!
I have the same mistake with you, Can I see the error settings for you to correct my code
